#!/bin/bash

# script: CreateEmptyDB
action="CreateEmptyDB"
actionversion="0.1; 2020-10-20"
#
# aim: create en empty sqlite3 database from the provided dump (structure only)
# note: if the output exists, first rename the existing file with timestamp
#   to avoid erroneous usage, you then need to re-run the command

########################################################################
# Edit here if necessary

####################### no edits below this line #######################

# sqlite3 variables
databasepath=$CONF_database_path
databasename=$CONF_database_name
dbversion=$CONF_database_version
dbcreatedate=$(date)
databasedump=$CONF_database_dump

# date-tag
actiondate=$(date +%s)

# creator
creator=${action}
creatorversion=${actionversion}

# create database from dump if not existing
if [ -f "${databasepath}/${databasename}" ]; then
	echo "# database ${databasename} already exists in ${databasepath}"
	echo "# creating a backup copy in ${databasepath}/backups/${databasename%.sqlite}_${actiondate}.sqlite"
	mv "${databasepath}/${databasename}" \
		"${databasepath}/backups/${databasename%.sqlite}_${actiondate}.sqlite"
	echo "# please re-run the current command now"
else
	sqlite3 -init "${databasedump}" "${databasepath}/${databasename}" ""
	# check for success
	if [ $? -eq 0 ]; then
		echo "# database ${databasename} was created in ${databasepath}"
		cmd="sqlite3 ${CONF_database_path}/${CONF_database_name} ${q}INSERT INTO version (vnum, vdate) VALUES (${d}${dbversion}${d}, ${d}${dbcreatedate}${d})${q};"
		# echo "# ${cmd}"
		eval ${cmd}
	else
		echo "# failed to create the database"
		exit 1
	fi
fi
