#!/bin/bash

# script: SetProjectNumber
action="SetProjectNumber"
actionversion="0.1; 2020-10-02"
#
# aim: manually set ProjectNumber for a given FolderName + FolderName

usage='# Usage: '${scriptname}' -a '${action}' -p folderpath=<FolderPath> -p foldername=<FolderName> -p projectnumber=<expXXXX-expYYYY ('null' for blank)>
optionally add -p comment=<comment>
# script version '${actionversion}

########################################################################
# Edit local variables here if necessary

# passed though ${opt_actparams[@]}
a_comment=${comment:-""}

####################### no edits below this line #######################

# sqlite3 and share variables
databasepath=${CONF_database_path}
databasename=${CONF_database_name}
mountpoint=${CONF_mount_transfer_point}
mountpath=${CONF_mount_transfer_path}

# timestamp for tmp file
ts=$(date +%s)
lts=$(date -r ${ts})

# creator
creator=${action}
creatorversion=${actionversion}

# Folderpath provided via ${opt_actparams[@]} ?
if [ -z "${folderpath}" ]
then
  echo "# no Folder Path provided"
  echo "${usage}"
  exit 1
fi

# FolderName provided via ${opt_actparams[@]} ?
if [ -z "${foldername}" ]
then
  echo "# no Folder Name provided"
  echo "${usage}"
  exit 1
fi

# ProjectNumber provided via ${opt_actparams[@]} ?
if [ -z "${projectnumber}" ]
then
  echo "# no ProjectNumber provided"
  echo "${usage}"
  exit 1
fi

# check folderpath+foldername exists and get current status
cmd="sqlite3 ${d}${databasepath}/${databasename}${d} ${q}SELECT FolderID, FolderPath, FolderName, ProjectNR FROM Folders WHERE FolderPath=${d}${folderpath}${d} AND FolderName=${d}${foldername}${d};${q}"
# echo "# ${cmd}"
row=$(eval ${cmd} )
# split row into array
curdata=( $(split2array ${row}) )

curprojnum=${curdata[3]:-""}

case ${projectnumber} in
  null)
      setprojnum="" ;;
  *) 
      setprojnum=${projectnumber} ;;
esac

# test if ProjectNumber is unchanged
[ "${setprojnum}" == "${curprojnum}" ] && { >&2 echo "# already set to this Project(s), quitting"; exit 0; }

# prepare a SQL script to set the Folder Status in the DB 
# and add action record in a single sqlite3 session
# write script file header

cat << END_BLOCK >> tmp/cmd_${ts}.sql
/*
------------------------------------------------------------------
written by '${action}'
date: '${lts}'
ts: '${ts}'
------------------------------------------------------------------
*/

PRAGMA foreign_keys = false;

/*
------------------------------------------------------------------
updating size for '${folderpath}/${foldername}
------------------------------------------------------------------
*/

UPDATE Folders
SET ProjectNR=${q}${setprojnum}${q}
WHERE FolderPath=${q}${curdata[1]}${q}
AND FolderName=${q}${curdata[2]}${q};

/*
------------------------------------------------------------------
adding data in Actions for ${folderpath}/${foldername}
------------------------------------------------------------------
*/

INSERT INTO Actions 
  (
  FolderID,
  Creator, 
  CreatorVersion, 
  ActionDate, 
  ActionName, 
  Comment
  )
VALUES (
  ${curdata[0]},
  ${d}${creator}${d}, 
  ${d}${creatorversion}${d}, 
  ${d}${ts}${d}, 
  ${d}${action}${d}, 
  ${d}changed from ${q}${curprojnum}${q} to ${q}${setprojnum}${q} (${a_comment})${d}
  );

-- ----------------------------------------------------------------

PRAGMA foreign_keys = false;

END_BLOCK

# else execute file and cleanup
cmd="sqlite3 ${d}${CONF_database_path}/${CONF_database_name}${d} ${d}.read ${CONF_database_path}/tmp/cmd_${ts}.sql${d};"
# echo "# ${cmd}"
eval ${cmd} && rm tmp/cmd_${ts}.sql

exit 0
